version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: nestjs-queue-postgres
    environment:
      POSTGRES_DB: queue_db
      POSTGRES_USER: queue_user
      POSTGRES_PASSWORD: queue_password
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U queue_user -d queue_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: